[DB]i[DB]m[DB]p[DB]o[DB]r[DB]t[DB] [DB]o[DB]s[DB]
[DB]f[DB]r[DB]o[DB]m[DB] [DB]p[DB]a[DB]t[DB]h[DB]l[DB]i[DB]b[DB] [DB]i[DB]m[DB]p[DB]o[DB]r[DB]t[DB] [DB]P[DB]a[DB]t[DB]h[DB]
[DB]f[DB]r[DB]o[DB]m[DB] [DB]u[DB]r[DB]l[DB]l[DB]i[DB]b[DB].[DB]p[DB]a[DB]r[DB]s[DB]e[DB] [DB]i[DB]m[DB]p[DB]o[DB]r[DB]t[DB] [DB]u[DB]r[DB]l[DB]p[DB]a[DB]r[DB]s[DB]e[DB]
[DB]
[DB]b[DB]a[DB]s[DB]e[DB]d[DB]i[DB]r[DB] [DB]=[DB] [DB]P[DB]a[DB]t[DB]h[DB]([DB]_[DB]_[DB]f[DB]i[DB]l[DB]e[DB]_[DB]_[DB])[DB].[DB]p[DB]a[DB]r[DB]e[DB]n[DB]t[DB].[DB]a[DB]b[DB]s[DB]o[DB]l[DB]u[DB]t[DB]e[DB]([DB])[DB]
[DB]d[DB]b[DB]_[DB]p[DB]a[DB]t[DB]h[DB] [DB]=[DB] [DB]P[DB]a[DB]t[DB]h[DB]([DB]"[DB]c[DB]:[DB]/[DB]t[DB]e[DB]m[DB]p[DB]/[DB]m[DB]e[DB]r[DB]c[DB]a[DB]d[DB]i[DB]n[DB]h[DB]o[DB]_[DB]i[DB]n[DB]s[DB]t[DB]a[DB]n[DB]c[DB]e[DB]/[DB]m[DB]e[DB]r[DB]c[DB]a[DB]d[DB]i[DB]n[DB]h[DB]o[DB].[DB]d[DB]b[DB]"[DB])[DB]
[DB]
[DB]
[DB]c[DB]l[DB]a[DB]s[DB]s[DB] [DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB]:[DB]
[DB] [DB] [DB] [DB] [DB]S[DB]E[DB]C[DB]R[DB]E[DB]T[DB]_[DB]K[DB]E[DB]Y[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]S[DB]E[DB]C[DB]R[DB]E[DB]T[DB]_[DB]K[DB]E[DB]Y[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]J[DB]W[DB]T[DB]_[DB]S[DB]E[DB]C[DB]R[DB]E[DB]T[DB]_[DB]K[DB]E[DB]Y[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]J[DB]W[DB]T[DB]_[DB]S[DB]E[DB]C[DB]R[DB]E[DB]T[DB]_[DB]K[DB]E[DB]Y[DB]"[DB])[DB]
[DB]
[DB] [DB] [DB] [DB] [DB]#[DB] [DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB] [DB]C[DB]O[DB]N[DB]F[DB]I[DB]G[DB]U[DB]R[DB]A[DB]T[DB]I[DB]O[DB]N[DB] [DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]
[DB] [DB] [DB] [DB] [DB]#[DB] [DB]S[DB]i[DB]s[DB]t[DB]e[DB]m[DB]a[DB] [DB]i[DB]n[DB]t[DB]e[DB]l[DB]i[DB]g[DB]e[DB]n[DB]t[DB]e[DB]:[DB] [DB]d[DB]e[DB]t[DB]e[DB]c[DB]t[DB]a[DB] [DB]a[DB]u[DB]t[DB]o[DB]m[DB]a[DB]t[DB]i[DB]c[DB]a[DB]m[DB]e[DB]n[DB]t[DB]e[DB] [DB]l[DB]o[DB]c[DB]a[DB]l[DB] [DB]v[DB]s[DB] [DB]n[DB]u[DB]v[DB]e[DB]m[DB]
[DB] [DB] [DB] [DB] [DB]
[DB] [DB] [DB] [DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]S[DB]Q[DB]L[DB]I[DB]T[DB]E[DB]_[DB]D[DB]B[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]S[DB]Q[DB]L[DB]I[DB]T[DB]E[DB]_[DB]D[DB]B[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]
[DB] [DB] [DB] [DB] [DB]#[DB] [DB]D[DB]e[DB]t[DB]e[DB]c[DB]t[DB]a[DB]r[DB] [DB]a[DB]m[DB]b[DB]i[DB]e[DB]n[DB]t[DB]e[DB]
[DB] [DB] [DB] [DB] [DB]I[DB]S[DB]_[DB]P[DB]R[DB]O[DB]D[DB]U[DB]C[DB]T[DB]I[DB]O[DB]N[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]R[DB]E[DB]N[DB]D[DB]E[DB]R[DB]"[DB])[DB] [DB]o[DB]r[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]R[DB]A[DB]I[DB]L[DB]W[DB]A[DB]Y[DB]"[DB])[DB] [DB]o[DB]r[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]H[DB]E[DB]R[DB]O[DB]K[DB]U[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]
[DB] [DB] [DB] [DB] [DB]i[DB]f[DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB]:[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]#[DB] [DB]N[DB]u[DB]v[DB]e[DB]m[DB]:[DB] [DB]P[DB]o[DB]s[DB]t[DB]g[DB]r[DB]e[DB]S[DB]Q[DB]L[DB] [DB]([DB]N[DB]e[DB]o[DB]n[DB],[DB] [DB]R[DB]e[DB]n[DB]d[DB]e[DB]r[DB],[DB] [DB]e[DB]t[DB]c[DB])[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]i[DB]f[DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB].[DB]s[DB]t[DB]a[DB]r[DB]t[DB]s[DB]w[DB]i[DB]t[DB]h[DB]([DB]"[DB]p[DB]o[DB]s[DB]t[DB]g[DB]r[DB]e[DB]s[DB]:[DB]/[DB]/[DB]"[DB])[DB]:[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB] [DB]=[DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB].[DB]r[DB]e[DB]p[DB]l[DB]a[DB]c[DB]e[DB]([DB]"[DB]p[DB]o[DB]s[DB]t[DB]g[DB]r[DB]e[DB]s[DB]:[DB]/[DB]/[DB]"[DB],[DB] [DB]"[DB]p[DB]o[DB]s[DB]t[DB]g[DB]r[DB]e[DB]s[DB]q[DB]l[DB]:[DB]/[DB]/[DB]"[DB],[DB] [DB]1[DB])[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]S[DB]Q[DB]L[DB]A[DB]L[DB]C[DB]H[DB]E[DB]M[DB]Y[DB]_[DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]I[DB] [DB]=[DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]p[DB]r[DB]i[DB]n[DB]t[DB]([DB]f[DB]"[DB][DB]ü[DB]å[DB]ê[DB] [DB][[DB]C[DB]L[DB]O[DB]U[DB]D[DB]][DB] [DB]U[DB]s[DB]i[DB]n[DB]g[DB] [DB]P[DB]o[DB]s[DB]t[DB]g[DB]r[DB]e[DB]S[DB]Q[DB]L[DB]:[DB] [DB]{[DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB].[DB]s[DB]p[DB]l[DB]i[DB]t[DB]([DB]'[DB]@[DB]'[DB])[DB][[DB]1[DB]][DB] [DB]i[DB]f[DB] [DB]'[DB]@[DB]'[DB] [DB]i[DB]n[DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB] [DB]e[DB]l[DB]s[DB]e[DB] [DB]'[DB]c[DB]l[DB]o[DB]u[DB]d[DB]'[DB]}[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]e[DB]l[DB]i[DB]f[DB] [DB]S[DB]Q[DB]L[DB]I[DB]T[DB]E[DB]_[DB]D[DB]B[DB]:[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]#[DB] [DB]L[DB]o[DB]c[DB]a[DB]l[DB]:[DB] [DB]S[DB]Q[DB]L[DB]i[DB]t[DB]e[DB] [DB]c[DB]u[DB]s[DB]t[DB]o[DB]m[DB]i[DB]z[DB]a[DB]d[DB]o[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]S[DB]Q[DB]L[DB]A[DB]L[DB]C[DB]H[DB]E[DB]M[DB]Y[DB]_[DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]I[DB] [DB]=[DB] [DB]S[DB]Q[DB]L[DB]I[DB]T[DB]E[DB]_[DB]D[DB]B[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]p[DB]r[DB]i[DB]n[DB]t[DB]([DB]f[DB]"[DB][DB]ü[DB]í[DB]æ[DB] [DB][[DB]L[DB]O[DB]C[DB]A[DB]L[DB]][DB] [DB]U[DB]s[DB]i[DB]n[DB]g[DB] [DB]S[DB]Q[DB]L[DB]i[DB]t[DB]e[DB]:[DB] [DB]{[DB]S[DB]Q[DB]L[DB]I[DB]T[DB]E[DB]_[DB]D[DB]B[DB]}[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]e[DB]l[DB]s[DB]e[DB]:[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]#[DB] [DB]F[DB]a[DB]l[DB]l[DB]b[DB]a[DB]c[DB]k[DB]:[DB] [DB]S[DB]Q[DB]L[DB]i[DB]t[DB]e[DB] [DB]p[DB]a[DB]d[DB]r[DB]√[DB]£[DB]o[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]S[DB]Q[DB]L[DB]A[DB]L[DB]C[DB]H[DB]E[DB]M[DB]Y[DB]_[DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]I[DB] [DB]=[DB] [DB]"[DB]s[DB]q[DB]l[DB]i[DB]t[DB]e[DB]:[DB]/[DB]/[DB]/[DB]c[DB]:[DB]/[DB]t[DB]e[DB]m[DB]p[DB]/[DB]m[DB]e[DB]r[DB]c[DB]a[DB]d[DB]i[DB]n[DB]h[DB]o[DB]_[DB]i[DB]n[DB]s[DB]t[DB]a[DB]n[DB]c[DB]e[DB]/[DB]m[DB]e[DB]r[DB]c[DB]a[DB]d[DB]i[DB]n[DB]h[DB]o[DB].[DB]d[DB]b[DB]"[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]p[DB]r[DB]i[DB]n[DB]t[DB]([DB]f[DB]"[DB][DB]ü[DB]í[DB]æ[DB] [DB][[DB]L[DB]O[DB]C[DB]A[DB]L[DB]][DB] [DB]U[DB]s[DB]i[DB]n[DB]g[DB] [DB]S[DB]Q[DB]L[DB]i[DB]t[DB]e[DB] [DB]([DB]d[DB]e[DB]f[DB]a[DB]u[DB]l[DB]t[DB])[DB]:[DB] [DB]{[DB]S[DB]Q[DB]L[DB]A[DB]L[DB]C[DB]H[DB]E[DB]M[DB]Y[DB]_[DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]I[DB]}[DB]"[DB])[DB]
[DB]
[DB] [DB] [DB] [DB] [DB]S[DB]Q[DB]L[DB]A[DB]L[DB]C[DB]H[DB]E[DB]M[DB]Y[DB]_[DB]T[DB]R[DB]A[DB]C[DB]K[DB]_[DB]M[DB]O[DB]D[DB]I[DB]F[DB]I[DB]C[DB]A[DB]T[DB]I[DB]O[DB]N[DB]S[DB] [DB]=[DB] [DB]F[DB]a[DB]l[DB]s[DB]e[DB]
[DB] [DB] [DB] [DB] [DB]S[DB]Q[DB]L[DB]A[DB]L[DB]C[DB]H[DB]E[DB]M[DB]Y[DB]_[DB]E[DB]N[DB]G[DB]I[DB]N[DB]E[DB]_[DB]O[DB]P[DB]T[DB]I[DB]O[DB]N[DB]S[DB] [DB]=[DB] [DB]{[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]"[DB]p[DB]o[DB]o[DB]l[DB]_[DB]p[DB]r[DB]e[DB]_[DB]p[DB]i[DB]n[DB]g[DB]"[DB]:[DB] [DB]T[DB]r[DB]u[DB]e[DB],[DB] [DB] [DB]#[DB] [DB]V[DB]e[DB]r[DB]i[DB]f[DB]i[DB]c[DB]a[DB] [DB]c[DB]o[DB]n[DB]e[DB]x[DB]√[DB]£[DB]o[DB] [DB]a[DB]n[DB]t[DB]e[DB]s[DB] [DB]d[DB]e[DB] [DB]u[DB]s[DB]a[DB]r[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]"[DB]p[DB]o[DB]o[DB]l[DB]_[DB]r[DB]e[DB]c[DB]y[DB]c[DB]l[DB]e[DB]"[DB]:[DB] [DB]3[DB]0[DB]0[DB],[DB] [DB] [DB] [DB] [DB]#[DB] [DB]R[DB]e[DB]c[DB]i[DB]c[DB]l[DB]a[DB] [DB]c[DB]o[DB]n[DB]e[DB]x[DB]√[DB]µ[DB]e[DB]s[DB] [DB]a[DB] [DB]c[DB]a[DB]d[DB]a[DB] [DB]5[DB] [DB]m[DB]i[DB]n[DB]u[DB]t[DB]o[DB]s[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]"[DB]p[DB]o[DB]o[DB]l[DB]_[DB]s[DB]i[DB]z[DB]e[DB]"[DB]:[DB] [DB]1[DB]0[DB],[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]#[DB] [DB]P[DB]o[DB]o[DB]l[DB] [DB]d[DB]e[DB] [DB]1[DB]0[DB] [DB]c[DB]o[DB]n[DB]e[DB]x[DB]√[DB]µ[DB]e[DB]s[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]"[DB]m[DB]a[DB]x[DB]_[DB]o[DB]v[DB]e[DB]r[DB]f[DB]l[DB]o[DB]w[DB]"[DB]:[DB] [DB]2[DB]0[DB],[DB] [DB] [DB] [DB] [DB] [DB]#[DB] [DB]A[DB]t[DB]√[DB]©[DB] [DB]2[DB]0[DB] [DB]c[DB]o[DB]n[DB]e[DB]x[DB]√[DB]µ[DB]e[DB]s[DB] [DB]e[DB]x[DB]t[DB]r[DB]a[DB]s[DB]
[DB] [DB] [DB] [DB] [DB]}[DB] [DB]i[DB]f[DB] [DB]D[DB]A[DB]T[DB]A[DB]B[DB]A[DB]S[DB]E[DB]_[DB]U[DB]R[DB]L[DB] [DB]e[DB]l[DB]s[DB]e[DB] [DB]{[DB]}[DB]
[DB]
[DB] [DB] [DB] [DB] [DB]#[DB] [DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB] [DB]C[DB]O[DB]R[DB]S[DB] [DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]
[DB] [DB] [DB] [DB] [DB]c[DB]o[DB]r[DB]s[DB]_[DB]o[DB]r[DB]i[DB]g[DB]i[DB]n[DB]s[DB]_[DB]s[DB]t[DB]r[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]C[DB]O[DB]R[DB]S[DB]_[DB]O[DB]R[DB]I[DB]G[DB]I[DB]N[DB]S[DB]"[DB],[DB] [DB]"[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]C[DB]O[DB]R[DB]S[DB]_[DB]O[DB]R[DB]I[DB]G[DB]I[DB]N[DB]S[DB] [DB]=[DB] [DB]([DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB][[DB]o[DB]r[DB]i[DB]g[DB]i[DB]n[DB].[DB]s[DB]t[DB]r[DB]i[DB]p[DB]([DB])[DB] [DB]f[DB]o[DB]r[DB] [DB]o[DB]r[DB]i[DB]g[DB]i[DB]n[DB] [DB]i[DB]n[DB] [DB]c[DB]o[DB]r[DB]s[DB]_[DB]o[DB]r[DB]i[DB]g[DB]i[DB]n[DB]s[DB]_[DB]s[DB]t[DB]r[DB].[DB]s[DB]p[DB]l[DB]i[DB]t[DB]([DB]"[DB],[DB]"[DB])[DB]][DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]i[DB]f[DB] [DB]c[DB]o[DB]r[DB]s[DB]_[DB]o[DB]r[DB]i[DB]g[DB]i[DB]n[DB]s[DB]_[DB]s[DB]t[DB]r[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]e[DB]l[DB]s[DB]e[DB] [DB][[DB]][DB]
[DB] [DB] [DB] [DB] [DB])[DB]
[DB]
[DB] [DB] [DB] [DB] [DB]#[DB] [DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB] [DB]E[DB]M[DB]A[DB]I[DB]L[DB] [DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]
[DB] [DB] [DB] [DB] [DB]M[DB]A[DB]I[DB]L[DB]_[DB]S[DB]E[DB]R[DB]V[DB]E[DB]R[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]M[DB]A[DB]I[DB]L[DB]_[DB]S[DB]E[DB]R[DB]V[DB]E[DB]R[DB]"[DB],[DB] [DB]"[DB]s[DB]m[DB]t[DB]p[DB].[DB]g[DB]m[DB]a[DB]i[DB]l[DB].[DB]c[DB]o[DB]m[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]M[DB]A[DB]I[DB]L[DB]_[DB]P[DB]O[DB]R[DB]T[DB] [DB]=[DB] [DB]i[DB]n[DB]t[DB]([DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]M[DB]A[DB]I[DB]L[DB]_[DB]P[DB]O[DB]R[DB]T[DB]"[DB],[DB] [DB]5[DB]8[DB]7[DB])[DB])[DB]
[DB] [DB] [DB] [DB] [DB]M[DB]A[DB]I[DB]L[DB]_[DB]U[DB]S[DB]E[DB]_[DB]T[DB]L[DB]S[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]M[DB]A[DB]I[DB]L[DB]_[DB]U[DB]S[DB]E[DB]_[DB]T[DB]L[DB]S[DB]"[DB],[DB] [DB]"[DB]t[DB]r[DB]u[DB]e[DB]"[DB])[DB].[DB]l[DB]o[DB]w[DB]e[DB]r[DB]([DB])[DB] [DB]=[DB]=[DB] [DB]"[DB]t[DB]r[DB]u[DB]e[DB]"[DB]
[DB] [DB] [DB] [DB] [DB]M[DB]A[DB]I[DB]L[DB]_[DB]U[DB]S[DB]E[DB]_[DB]S[DB]S[DB]L[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]M[DB]A[DB]I[DB]L[DB]_[DB]U[DB]S[DB]E[DB]_[DB]S[DB]S[DB]L[DB]"[DB],[DB] [DB]"[DB]f[DB]a[DB]l[DB]s[DB]e[DB]"[DB])[DB].[DB]l[DB]o[DB]w[DB]e[DB]r[DB]([DB])[DB] [DB]=[DB]=[DB] [DB]"[DB]t[DB]r[DB]u[DB]e[DB]"[DB]
[DB] [DB] [DB] [DB] [DB]M[DB]A[DB]I[DB]L[DB]_[DB]U[DB]S[DB]E[DB]R[DB]N[DB]A[DB]M[DB]E[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]M[DB]A[DB]I[DB]L[DB]_[DB]U[DB]S[DB]E[DB]R[DB]N[DB]A[DB]M[DB]E[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]M[DB]A[DB]I[DB]L[DB]_[DB]P[DB]A[DB]S[DB]S[DB]W[DB]O[DB]R[DB]D[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]M[DB]A[DB]I[DB]L[DB]_[DB]P[DB]A[DB]S[DB]S[DB]W[DB]O[DB]R[DB]D[DB]"[DB])[DB]
[DB] [DB] [DB] [DB] [DB]M[DB]A[DB]I[DB]L[DB]_[DB]D[DB]E[DB]F[DB]A[DB]U[DB]L[DB]T[DB]_[DB]S[DB]E[DB]N[DB]D[DB]E[DB]R[DB] [DB]=[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]M[DB]A[DB]I[DB]L[DB]_[DB]D[DB]E[DB]F[DB]A[DB]U[DB]L[DB]T[DB]_[DB]S[DB]E[DB]N[DB]D[DB]E[DB]R[DB]"[DB],[DB] [DB]o[DB]s[DB].[DB]e[DB]n[DB]v[DB]i[DB]r[DB]o[DB]n[DB].[DB]g[DB]e[DB]t[DB]([DB]"[DB]M[DB]A[DB]I[DB]L[DB]_[DB]U[DB]S[DB]E[DB]R[DB]N[DB]A[DB]M[DB]E[DB]"[DB])[DB])[DB]
[DB]
[DB] [DB] [DB] [DB] [DB]#[DB] [DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB] [DB]J[DB]W[DB]T[DB] [DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]=[DB]
[DB] [DB] [DB] [DB] [DB]J[DB]W[DB]T[DB]_[DB]A[DB]C[DB]C[DB]E[DB]S[DB]S[DB]_[DB]T[DB]O[DB]K[DB]E[DB]N[DB]_[DB]E[DB]X[DB]P[DB]I[DB]R[DB]E[DB]S[DB] [DB]=[DB] [DB]3[DB]6[DB]0[DB]0[DB]
[DB] [DB] [DB] [DB] [DB]J[DB]W[DB]T[DB]_[DB]R[DB]E[DB]F[DB]R[DB]E[DB]S[DB]H[DB]_[DB]T[DB]O[DB]K[DB]E[DB]N[DB]_[DB]E[DB]X[DB]P[DB]I[DB]R[DB]E[DB]S[DB] [DB]=[DB] [DB]6[DB]0[DB]4[DB]8[DB]0[DB]0[DB] [DB] [DB]#[DB] [DB]7[DB] [DB]d[DB]i[DB]a[DB]s[DB]
[DB]
[DB]
[DB]c[DB]l[DB]a[DB]s[DB]s[DB] [DB]D[DB]e[DB]v[DB]e[DB]l[DB]o[DB]p[DB]m[DB]e[DB]n[DB]t[DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB]([DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB])[DB]:[DB]
[DB] [DB] [DB] [DB] [DB]D[DB]E[DB]B[DB]U[DB]G[DB] [DB]=[DB] [DB]T[DB]r[DB]u[DB]e[DB]
[DB] [DB] [DB] [DB] [DB]i[DB]f[DB] [DB]n[DB]o[DB]t[DB] [DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB].[DB]C[DB]O[DB]R[DB]S[DB]_[DB]O[DB]R[DB]I[DB]G[DB]I[DB]N[DB]S[DB]:[DB]
[DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB] [DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB].[DB]C[DB]O[DB]R[DB]S[DB]_[DB]O[DB]R[DB]I[DB]G[DB]I[DB]N[DB]S[DB] [DB]=[DB] [DB][[DB]"[DB]h[DB]t[DB]t[DB]p[DB]:[DB]/[DB]/[DB]l[DB]o[DB]c[DB]a[DB]l[DB]h[DB]o[DB]s[DB]t[DB]:[DB]3[DB]0[DB]0[DB]0[DB]"[DB],[DB] [DB]"[DB]h[DB]t[DB]t[DB]p[DB]:[DB]/[DB]/[DB]l[DB]o[DB]c[DB]a[DB]l[DB]h[DB]o[DB]s[DB]t[DB]:[DB]5[DB]1[DB]7[DB]3[DB]"[DB]][DB]
[DB]
[DB]
[DB]c[DB]l[DB]a[DB]s[DB]s[DB] [DB]P[DB]r[DB]o[DB]d[DB]u[DB]c[DB]t[DB]i[DB]o[DB]n[DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB]([DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB])[DB]:[DB]
[DB] [DB] [DB] [DB] [DB]D[DB]E[DB]B[DB]U[DB]G[DB] [DB]=[DB] [DB]F[DB]a[DB]l[DB]s[DB]e[DB]
[DB] [DB] [DB] [DB] [DB]#[DB] [DB]F[DB]o[DB]r[DB]√[DB]ß[DB]a[DB]r[DB] [DB]H[DB]T[DB]T[DB]P[DB]S[DB] [DB]e[DB]m[DB] [DB]p[DB]r[DB]o[DB]d[DB]u[DB]√[DB]ß[DB]√[DB]£[DB]o[DB]
[DB] [DB] [DB] [DB] [DB]P[DB]R[DB]E[DB]F[DB]E[DB]R[DB]R[DB]E[DB]D[DB]_[DB]U[DB]R[DB]L[DB]_[DB]S[DB]C[DB]H[DB]E[DB]M[DB]E[DB] [DB]=[DB] [DB]'[DB]h[DB]t[DB]t[DB]p[DB]s[DB]'[DB]
[DB]
[DB]
[DB]c[DB]o[DB]n[DB]f[DB]i[DB]g[DB] [DB]=[DB] [DB]{[DB]
[DB] [DB] [DB] [DB] [DB]"[DB]d[DB]e[DB]v[DB]e[DB]l[DB]o[DB]p[DB]m[DB]e[DB]n[DB]t[DB]"[DB]:[DB] [DB]D[DB]e[DB]v[DB]e[DB]l[DB]o[DB]p[DB]m[DB]e[DB]n[DB]t[DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB],[DB]
[DB] [DB] [DB] [DB] [DB]"[DB]p[DB]r[DB]o[DB]d[DB]u[DB]c[DB]t[DB]i[DB]o[DB]n[DB]"[DB]:[DB] [DB]P[DB]r[DB]o[DB]d[DB]u[DB]c[DB]t[DB]i[DB]o[DB]n[DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB],[DB]
[DB] [DB] [DB] [DB] [DB]"[DB]d[DB]e[DB]f[DB]a[DB]u[DB]l[DB]t[DB]"[DB]:[DB] [DB]D[DB]e[DB]v[DB]e[DB]l[DB]o[DB]p[DB]m[DB]e[DB]n[DB]t[DB]C[DB]o[DB]n[DB]f[DB]i[DB]g[DB],[DB]
[DB]}[DB]
