""" Adiciona modelo AbastecimentoVeiculo

Revision ID: 07476b2a790d
Revises: d2299b1ad288
Create Date: 2026-07-07 18:17:17.539947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07476b2a790d'
down_revision = 'd2299b1ad288'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abastecimentos_veiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=False),
    sa.Column('data_abastecimento', sa.DateTime(), nullable=True),
    sa.Column('km_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('litros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_litro', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('tipo_combustivel', sa.String(length=20), nullable=True),
    sa.Column('km_rodados_desde_ultimo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('consumo_real_kml', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('fk_abastecimentos_veiculos_estabelecimento_id_estabelecimentos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motorista_id'], ['motoristas.id'], name=op.f('fk_abastecimentos_veiculos_motorista_id_motoristas')),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], name=op.f('fk_abastecimentos_veiculos_veiculo_id_veiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_abastecimentos_veiculos'))
    )
    with op.batch_alter_table('abastecimentos_veiculos', schema=None) as batch_op:
        batch_op.create_index('ix_abast_veic_estab', ['estabelecimento_id', 'veiculo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abastecimentos_veiculos_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abastecimentos_veiculos_motorista_id'), ['motorista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_abastecimentos_veiculos_veiculo_id'), ['veiculo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('abastecimentos_veiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_abastecimentos_veiculos_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_abastecimentos_veiculos_motorista_id'))
        batch_op.drop_index(batch_op.f('ix_abastecimentos_veiculos_estabelecimento_id'))
        batch_op.drop_index('ix_abast_veic_estab')

    op.drop_table('abastecimentos_veiculos')
    # ### end Alembic commands ###
