"""SFA V2

Revision ID: 084a01492b51
Revises: f8efae926d7f
Create Date: 2026-06-30 23:06:44.259692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '084a01492b51'
down_revision = 'f8efae926d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendedor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_clientes_vendedor_id_funcionarios'), 'funcionarios', ['vendedor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clientes_vendedor_id_funcionarios'), type_='foreignkey')
        batch_op.drop_column('vendedor_id')

    # ### end Alembic commands ###
