"""feat(logistica): Add ConfiguracaoLogistica and TurnoEntregador models

Revision ID: 0c1bd4990ca0
Revises: 116b2f03b202
Create Date: 2026-07-06 17:23:40.592805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1bd4990ca0'
down_revision = '116b2f03b202'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracoes_logistica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('preco_gasolina', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_alcool', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('preco_diesel', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manutencao_moto_diaria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manutencao_carro_diaria', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('fk_configuracoes_logistica_estabelecimento_id_estabelecimentos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_configuracoes_logistica'))
    )
    with op.batch_alter_table('configuracoes_logistica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_configuracoes_logistica_estabelecimento_id'), ['estabelecimento_id'], unique=False)

    op.create_table('turnos_entregador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=True),
    sa.Column('data_turno', sa.Date(), nullable=False),
    sa.Column('horario_inicio', sa.DateTime(), nullable=True),
    sa.Column('horario_fim', sa.DateTime(), nullable=True),
    sa.Column('km_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('km_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('distancia_percorrida', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_combustivel', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('custo_manutencao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_combustivel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('fk_turnos_entregador_estabelecimento_id_estabelecimentos')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('fk_turnos_entregador_funcionario_id_funcionarios')),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], name=op.f('fk_turnos_entregador_veiculo_id_veiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turnos_entregador'))
    )
    with op.batch_alter_table('turnos_entregador', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turnos_entregador_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turnos_entregador_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_turnos_entregador_veiculo_id'), ['veiculo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turnos_entregador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turnos_entregador_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_turnos_entregador_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_turnos_entregador_estabelecimento_id'))

    op.drop_table('turnos_entregador')
    with op.batch_alter_table('configuracoes_logistica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_configuracoes_logistica_estabelecimento_id'))

    op.drop_table('configuracoes_logistica')
    # ### end Alembic commands ###
