"""Logistica

Revision ID: 116b2f03b202
Revises: b4d6f8a0c2e3
Create Date: 2026-07-06 00:42:48.845108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '116b2f03b202'
down_revision = 'b4d6f8a0c2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_quilometragem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('turno_data', sa.Date(), nullable=False),
    sa.Column('pontos_gps', sa.JSON(), nullable=True),
    sa.Column('distancia_total_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('fk_auditoria_quilometragem_estabelecimento_id_estabelecimentos')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('fk_auditoria_quilometragem_funcionario_id_funcionarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditoria_quilometragem'))
    )
    with op.batch_alter_table('auditoria_quilometragem', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_quilometragem_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditoria_quilometragem_funcionario_id'), ['funcionario_id'], unique=False)

    op.create_table('status_pedido_logistica',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('fk_status_pedido_logistica_estabelecimento_id_estabelecimentos')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('fk_status_pedido_logistica_funcionario_id_funcionarios')),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], name=op.f('fk_status_pedido_logistica_venda_id_vendas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_status_pedido_logistica'))
    )
    with op.batch_alter_table('status_pedido_logistica', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_status_pedido_logistica_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_pedido_logistica_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_status_pedido_logistica_venda_id'), ['venda_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status_pedido_logistica', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_status_pedido_logistica_venda_id'))
        batch_op.drop_index(batch_op.f('ix_status_pedido_logistica_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_status_pedido_logistica_estabelecimento_id'))

    op.drop_table('status_pedido_logistica')
    with op.batch_alter_table('auditoria_quilometragem', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_quilometragem_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_auditoria_quilometragem_estabelecimento_id'))

    op.drop_table('auditoria_quilometragem')
    # ### end Alembic commands ###
