"""ajuste final Cliente

Revision ID: 1575c4174213
Revises: 5590a2d593c3
Create Date: 2026-01-06 01:15:18.978832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1575c4174213'
down_revision = '5590a2d593c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_compras', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('ultima_compra', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('frequencia_compras', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_medio_compra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dias_ultima_compra', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('segmento_rfm', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('segmento_rfm')
        batch_op.drop_column('dias_ultima_compra')
        batch_op.drop_column('valor_medio_compra')
        batch_op.drop_column('frequencia_compras')
        batch_op.drop_column('ultima_compra')
        batch_op.drop_column('total_compras')

    # ### end Alembic commands ###
