"""Added CondicaoPagamento

Revision ID: 1e7f4460e868
Revises: 084a01492b51
Create Date: 2026-07-01 18:40:38.577866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e7f4460e868'
down_revision = '084a01492b51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_geral', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('atraso_medio_dias', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('percentual_entregas_no_prazo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('desconto_medio_percentual', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prazo_pagamento_medio_dias', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_column('prazo_pagamento_medio_dias')
        batch_op.drop_column('desconto_medio_percentual')
        batch_op.drop_column('percentual_entregas_no_prazo')
        batch_op.drop_column('atraso_medio_dias')
        batch_op.drop_column('score_geral')

    # ### end Alembic commands ###
