"""Adicionar despesas

Revision ID: 2b2c732fc099
Revises: 
Create Date: 2026-01-02 00:13:34.358814

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '2b2c732fc099'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analises_preditivas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('metricas', sa.JSON(), nullable=True),
    sa.Column('dados_treinamento_inicio', sa.Date(), nullable=True),
    sa.Column('dados_treinamento_fim', sa.Date(), nullable=True),
    sa.Column('tamanho_treinamento', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ultimo_treinamento', sa.DateTime(), nullable=True),
    sa.Column('proximo_treinamento', sa.DateTime(), nullable=True),
    sa.Column('precisao', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_despesa', sa.Date(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesas_estabelecimento_id'), ['estabelecimento_id'], unique=False)

    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('dispositivo', sa.String(length=200), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('token_hash', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequencia_compras', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_medio_compra', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('dias_ultima_compra', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('segmento_rfm', sa.String(length=20), nullable=True))

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_vendas_diaria', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('meta_vendas_mensal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alerta_estoque_minimo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alerta_validade_proxima', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('alerta_churn_clientes', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('dashboard_analytics_avancado', sa.Boolean(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('logo_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('cor_principal',
               existing_type=sa.TEXT(),
               type_=sa.String(length=7),
               existing_nullable=True,
               existing_server_default=sa.text("'#4F46E5'"))
        batch_op.alter_column('tipo_impressora',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'termica'"))
        batch_op.alter_column('desconto_maximo_percentual',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(10.0)'))
        batch_op.alter_column('arredondamento_valores',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.05)'))
        batch_op.alter_column('formas_pagamento',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('dashboard_metricas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_atingida_dia', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('meta_diaria', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('margem_lucro_mes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('crescimento_vs_ontem', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('crescimento_mensal', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tendencia_vendas', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('vendas_por_hora_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('padrao_semanal_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('sazonalidade_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('produtos_abc_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('cross_selling_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('segmentacao_clientes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('top_clientes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('taxa_churn', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('clv_medio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('alertas_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('insights_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('anomalias_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('previsoes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('confianca_previsao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comparativo_ontem_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comparativo_semana_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('comparativo_mes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tempo_resposta_medio', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('precisao_previsoes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('data_calculo', sa.DateTime(), nullable=True))
        batch_op.alter_column('top_produtos_json',
               existing_type=sqlite.JSON(),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.create_index('idx_metricas_data', ['data_referencia'], unique=False)
        batch_op.create_index('idx_metricas_estab_data', ['estabelecimento_id', 'data_referencia'], unique=False)
        batch_op.drop_column('produtos_validade_json')

    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('cnpj',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('estado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=2),
               existing_nullable=True)

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cidade', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('contato_nome', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ativo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('avaliacao', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tempo_medio_entrega', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('taxa_atendimento', sa.Float(), nullable=True))

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('nome',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('cpf',
               existing_type=sa.TEXT(),
               type_=sa.String(length=14),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('senha_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('foto_url',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('cargo',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'funcionario'"))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=True,
               existing_server_default=sa.text("'ativo'"))
        batch_op.alter_column('comissao_percentual',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('permissoes',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_unitario', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('valor_total', sa.Float(), nullable=True))

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcategoria', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('dias_estoque', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('giro_estoque', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_vendido', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('quantidade_vendida', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('frequencia_venda', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ultima_venda', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('classificação_abc', sa.String(length=1), nullable=True))

    with op.batch_alter_table('relatorios_agendados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('analises_incluidas', sa.JSON(), nullable=True))

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custo_unitario', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('margem_item', sa.Float(), nullable=True))

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_itens', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('tipo_venda', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_column('tipo_venda')
        batch_op.drop_column('quantidade_itens')

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.drop_column('margem_item')
        batch_op.drop_column('custo_unitario')

    with op.batch_alter_table('relatorios_agendados', schema=None) as batch_op:
        batch_op.drop_column('analises_incluidas')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('classificação_abc')
        batch_op.drop_column('ultima_venda')
        batch_op.drop_column('frequencia_venda')
        batch_op.drop_column('quantidade_vendida')
        batch_op.drop_column('total_vendido')
        batch_op.drop_column('giro_estoque')
        batch_op.drop_column('dias_estoque')
        batch_op.drop_column('subcategoria')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.drop_column('valor_total')
        batch_op.drop_column('custo_unitario')

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.alter_column('permissoes',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('comissao_percentual',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'ativo'"))
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'funcionario'"))
        batch_op.alter_column('cargo',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('foto_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('senha_hash',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cpf',
               existing_type=sa.String(length=14),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.drop_column('taxa_atendimento')
        batch_op.drop_column('tempo_medio_entrega')
        batch_op.drop_column('avaliacao')
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_cadastro')
        batch_op.drop_column('ativo')
        batch_op.drop_column('contato_nome')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')

    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.alter_column('estado',
               existing_type=sa.String(length=2),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('dashboard_metricas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('produtos_validade_json', sqlite.JSON(), nullable=True))
        batch_op.drop_index('idx_metricas_estab_data')
        batch_op.drop_index('idx_metricas_data')
        batch_op.alter_column('top_produtos_json',
               existing_type=sa.Text(),
               type_=sqlite.JSON(),
               existing_nullable=True)
        batch_op.drop_column('data_calculo')
        batch_op.drop_column('precisao_previsoes')
        batch_op.drop_column('tempo_resposta_medio')
        batch_op.drop_column('comparativo_mes_json')
        batch_op.drop_column('comparativo_semana_json')
        batch_op.drop_column('comparativo_ontem_json')
        batch_op.drop_column('confianca_previsao')
        batch_op.drop_column('previsoes_json')
        batch_op.drop_column('anomalias_json')
        batch_op.drop_column('insights_json')
        batch_op.drop_column('alertas_json')
        batch_op.drop_column('clv_medio')
        batch_op.drop_column('taxa_churn')
        batch_op.drop_column('top_clientes_json')
        batch_op.drop_column('segmentacao_clientes_json')
        batch_op.drop_column('cross_selling_json')
        batch_op.drop_column('produtos_abc_json')
        batch_op.drop_column('sazonalidade_json')
        batch_op.drop_column('padrao_semanal_json')
        batch_op.drop_column('vendas_por_hora_json')
        batch_op.drop_column('tendencia_vendas')
        batch_op.drop_column('crescimento_mensal')
        batch_op.drop_column('crescimento_vs_ontem')
        batch_op.drop_column('margem_lucro_mes')
        batch_op.drop_column('meta_diaria')
        batch_op.drop_column('meta_atingida_dia')

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.alter_column('formas_pagamento',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('arredondamento_valores',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.05)'))
        batch_op.alter_column('desconto_maximo_percentual',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(10.0)'))
        batch_op.alter_column('tipo_impressora',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'termica'"))
        batch_op.alter_column('cor_principal',
               existing_type=sa.String(length=7),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'#4F46E5'"))
        batch_op.alter_column('logo_url',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('dashboard_analytics_avancado')
        batch_op.drop_column('alerta_churn_clientes')
        batch_op.drop_column('alerta_validade_proxima')
        batch_op.drop_column('alerta_estoque_minimo')
        batch_op.drop_column('meta_vendas_mensal')
        batch_op.drop_column('meta_vendas_diaria')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('segmento_rfm')
        batch_op.drop_column('dias_ultima_compra')
        batch_op.drop_column('valor_medio_compra')
        batch_op.drop_column('frequencia_compras')

    op.drop_table('login_history')
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_estabelecimento_id'))

    op.drop_table('despesas')
    op.drop_table('analises_preditivas')
    # ### end Alembic commands ###
