"""add preco por km in logistica

Revision ID: 3bed2e4d3fea
Revises: 0c1bd4990ca0
Create Date: 2026-07-06 17:39:31.225872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bed2e4d3fea'
down_revision = '0c1bd4990ca0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes_logistica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_por_km_moto', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('preco_por_km_carro', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes_logistica', schema=None) as batch_op:
        batch_op.drop_column('preco_por_km_carro')
        batch_op.drop_column('preco_por_km_moto')

    # ### end Alembic commands ###
