"""cria todas as tabelas do zero

Revision ID: 5590a2d593c3
Revises: 
Create Date: 2026-01-06 01:11:06.566040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5590a2d593c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estabelecimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('analises_preditivas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('metricas', sa.JSON(), nullable=True),
    sa.Column('dados_treinamento_inicio', sa.Date(), nullable=True),
    sa.Column('dados_treinamento_fim', sa.Date(), nullable=True),
    sa.Column('tamanho_treinamento', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('ultimo_treinamento', sa.DateTime(), nullable=True),
    sa.Column('proximo_treinamento', sa.DateTime(), nullable=True),
    sa.Column('precisao', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_cpf_cnpj'), ['cpf_cnpj'], unique=True)

    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('cor_principal', sa.String(length=7), nullable=True),
    sa.Column('tema_escuro', sa.Boolean(), nullable=True),
    sa.Column('impressao_automatica', sa.Boolean(), nullable=True),
    sa.Column('tipo_impressora', sa.String(length=20), nullable=True),
    sa.Column('exibir_preco_tela', sa.Boolean(), nullable=True),
    sa.Column('permitir_venda_sem_estoque', sa.Boolean(), nullable=True),
    sa.Column('desconto_maximo_percentual', sa.Float(), nullable=True),
    sa.Column('arredondamento_valores', sa.Float(), nullable=True),
    sa.Column('dias_alerta_validade', sa.Integer(), nullable=True),
    sa.Column('estoque_minimo_padrao', sa.Integer(), nullable=True),
    sa.Column('tempo_sessao_minutos', sa.Integer(), nullable=True),
    sa.Column('tentativas_senha_bloqueio', sa.Integer(), nullable=True),
    sa.Column('formas_pagamento', sa.JSON(), nullable=True),
    sa.Column('meta_vendas_diaria', sa.Float(), nullable=True),
    sa.Column('meta_vendas_mensal', sa.Float(), nullable=True),
    sa.Column('alerta_estoque_minimo', sa.Boolean(), nullable=True),
    sa.Column('alerta_validade_proxima', sa.Boolean(), nullable=True),
    sa.Column('alerta_churn_clientes', sa.Boolean(), nullable=True),
    sa.Column('dashboard_analytics_avancado', sa.Boolean(), nullable=True),
    sa.Column('alertas_email', sa.Boolean(), nullable=True),
    sa.Column('alertas_whatsapp', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estabelecimento_id')
    )
    op.create_table('dashboard_metricas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('data_referencia', sa.Date(), nullable=False),
    sa.Column('total_vendas_dia', sa.Float(), nullable=True),
    sa.Column('quantidade_vendas_dia', sa.Integer(), nullable=True),
    sa.Column('ticket_medio_dia', sa.Float(), nullable=True),
    sa.Column('clientes_atendidos_dia', sa.Integer(), nullable=True),
    sa.Column('meta_atingida_dia', sa.Boolean(), nullable=True),
    sa.Column('meta_diaria', sa.Float(), nullable=True),
    sa.Column('total_vendas_mes', sa.Float(), nullable=True),
    sa.Column('total_despesas_mes', sa.Float(), nullable=True),
    sa.Column('lucro_bruto_mes', sa.Float(), nullable=True),
    sa.Column('margem_lucro_mes', sa.Float(), nullable=True),
    sa.Column('crescimento_vs_ontem', sa.Float(), nullable=True),
    sa.Column('crescimento_mensal', sa.Float(), nullable=True),
    sa.Column('tendencia_vendas', sa.String(length=20), nullable=True),
    sa.Column('vendas_por_hora_json', sa.Text(), nullable=True),
    sa.Column('padrao_semanal_json', sa.Text(), nullable=True),
    sa.Column('sazonalidade_json', sa.Text(), nullable=True),
    sa.Column('top_produtos_json', sa.Text(), nullable=True),
    sa.Column('produtos_abc_json', sa.Text(), nullable=True),
    sa.Column('cross_selling_json', sa.Text(), nullable=True),
    sa.Column('segmentacao_clientes_json', sa.Text(), nullable=True),
    sa.Column('top_clientes_json', sa.Text(), nullable=True),
    sa.Column('taxa_churn', sa.Float(), nullable=True),
    sa.Column('clv_medio', sa.Float(), nullable=True),
    sa.Column('alertas_json', sa.Text(), nullable=True),
    sa.Column('insights_json', sa.Text(), nullable=True),
    sa.Column('anomalias_json', sa.Text(), nullable=True),
    sa.Column('previsoes_json', sa.Text(), nullable=True),
    sa.Column('confianca_previsao', sa.Float(), nullable=True),
    sa.Column('comparativo_ontem_json', sa.Text(), nullable=True),
    sa.Column('comparativo_semana_json', sa.Text(), nullable=True),
    sa.Column('comparativo_mes_json', sa.Text(), nullable=True),
    sa.Column('tempo_resposta_medio', sa.Float(), nullable=True),
    sa.Column('precisao_previsoes', sa.Float(), nullable=True),
    sa.Column('data_calculo', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('estabelecimento_id', 'data_referencia', name='uix_estab_data')
    )
    with op.batch_alter_table('dashboard_metricas', schema=None) as batch_op:
        batch_op.create_index('idx_metricas_data', ['data_referencia'], unique=False)
        batch_op.create_index('idx_metricas_estab_data', ['estabelecimento_id', 'data_referencia'], unique=False)

    op.create_table('despesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=True),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('data_despesa', sa.Date(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesas_estabelecimento_id'), ['estabelecimento_id'], unique=False)

    op.create_table('fornecedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('cnpj', sa.String(length=20), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('endereco', sa.Text(), nullable=True),
    sa.Column('cidade', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('cep', sa.String(length=10), nullable=True),
    sa.Column('contato_comercial', sa.String(length=100), nullable=True),
    sa.Column('contato_nome', sa.String(length=100), nullable=True),
    sa.Column('celular_comercial', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_cadastro', sa.DateTime(), nullable=True),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=True),
    sa.Column('prazo_entrega', sa.Integer(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('avaliacao', sa.Float(), nullable=True),
    sa.Column('tempo_medio_entrega', sa.Integer(), nullable=True),
    sa.Column('taxa_atendimento', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=True),
    sa.Column('foto_url', sa.String(length=255), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('comissao_percentual', sa.Float(), nullable=True),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('data_demissao', sa.Date(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('permissoes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('username')
    )
    op.create_table('relatorios_agendados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('frequencia', sa.String(length=20), nullable=False),
    sa.Column('analises_incluidas', sa.JSON(), nullable=True),
    sa.Column('horario_envio', sa.Time(), nullable=False),
    sa.Column('destinatarios_email', sa.JSON(), nullable=True),
    sa.Column('enviar_para_proprietario', sa.Boolean(), nullable=True),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('ultima_execucao', sa.DateTime(), nullable=True),
    sa.Column('proxima_execucao', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('dispositivo', sa.String(length=200), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('token_hash', sa.Integer(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('fornecedor_id', sa.Integer(), nullable=True),
    sa.Column('codigo_barras', sa.String(length=50), nullable=True),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('marca', sa.String(length=50), nullable=True),
    sa.Column('fabricante', sa.String(length=50), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('subcategoria', sa.String(length=50), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.Column('unidade_medida', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=True),
    sa.Column('quantidade_minima', sa.Integer(), nullable=True),
    sa.Column('localizacao', sa.String(length=50), nullable=True),
    sa.Column('dias_estoque', sa.Integer(), nullable=True),
    sa.Column('giro_estoque', sa.Float(), nullable=True),
    sa.Column('preco_custo', sa.Float(), nullable=False),
    sa.Column('preco_venda', sa.Float(), nullable=False),
    sa.Column('margem_lucro', sa.Float(), nullable=True),
    sa.Column('total_vendido', sa.Float(), nullable=True),
    sa.Column('quantidade_vendida', sa.Integer(), nullable=True),
    sa.Column('frequencia_venda', sa.Integer(), nullable=True),
    sa.Column('ultima_venda', sa.DateTime(), nullable=True),
    sa.Column('classificação_abc', sa.String(length=1), nullable=True),
    sa.Column('data_fabricacao', sa.Date(), nullable=True),
    sa.Column('data_validade', sa.Date(), nullable=True),
    sa.Column('lote', sa.String(length=50), nullable=True),
    sa.Column('dias_para_vencer', sa.Integer(), nullable=True),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['fornecedor_id'], ['fornecedores.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_barras')
    )
    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('valor_recebido', sa.Float(), nullable=False),
    sa.Column('troco', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('quantidade_itens', sa.Integer(), nullable=True),
    sa.Column('tipo_venda', sa.String(length=20), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('data_cancelamento', sa.DateTime(), nullable=True),
    sa.Column('motivo_cancelamento', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=True),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('quantidade_anterior', sa.Integer(), nullable=False),
    sa.Column('quantidade_atual', sa.Integer(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('valor_total', sa.Float(), nullable=True),
    sa.Column('motivo', sa.String(length=100), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venda_itens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('produto_nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('produto_codigo', sa.String(length=50), nullable=True),
    sa.Column('produto_unidade', sa.String(length=20), nullable=True),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=True),
    sa.Column('total_item', sa.Float(), nullable=False),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.Column('margem_item', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venda_itens')
    op.drop_table('movimentacoes_estoque')
    op.drop_table('vendas')
    op.drop_table('produtos')
    op.drop_table('login_history')
    op.drop_table('relatorios_agendados')
    op.drop_table('funcionarios')
    op.drop_table('fornecedores')
    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_estabelecimento_id'))

    op.drop_table('despesas')
    with op.batch_alter_table('dashboard_metricas', schema=None) as batch_op:
        batch_op.drop_index('idx_metricas_estab_data')
        batch_op.drop_index('idx_metricas_data')

    op.drop_table('dashboard_metricas')
    op.drop_table('configuracoes')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_cpf_cnpj'))

    op.drop_table('clientes')
    op.drop_table('analises_preditivas')
    op.drop_table('estabelecimentos')
    # ### end Alembic commands ###
