"""Initial migration

Revision ID: 55cf8e93f552
Revises: add_saas_and_leads
Create Date: 2026-03-10 13:51:12.746993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55cf8e93f552'
down_revision = 'add_saas_and_leads'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banco_horas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('beneficios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('caixas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('categorias_produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_tolerancia_fiado', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('markup_padrao', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cor_primaria', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('cor_secundaria', sa.String(length=7), nullable=True))
        batch_op.add_column(sa.Column('tema', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('tipo_impressora',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)

    with op.batch_alter_table('configuracoes_horario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('contas_pagar', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('contas_receber', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('dashboard_metricas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefixo_venda', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('funciona_domingo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('regime_tributario',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.alter_column('plano',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('plano_status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_atualizacao')
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('funcionario_beneficios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_cadastro')
        batch_op.drop_column('salario')
        batch_op.drop_column('observacoes')

    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('justificativas_ponto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_login_history_data'))
        batch_op.create_index('idx_login_history_data', ['created_at'], unique=False)
        batch_op.drop_column('data_cadastro')

    with op.batch_alter_table('movimentacoes_caixa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
        batch_op.alter_column('quantidade_anterior',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
        batch_op.alter_column('quantidade_atual',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'produto_lotes', ['lote_id'], ['id'])

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('produto_lotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)
        batch_op.alter_column('quantidade_inicial',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True)
        batch_op.alter_column('quantidade_minima',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True)
        batch_op.alter_column('quantidade_vendida',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=True)
        batch_op.drop_column('giro_estoque')
        batch_op.drop_column('dias_estoque')

    with op.batch_alter_table('registros_ponto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('relatorios_agendados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('quantidade',
               existing_type=sa.INTEGER(),
               type_=sa.Numeric(precision=10, scale=3),
               existing_nullable=False)

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'caixas', ['caixa_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.alter_column('quantidade',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sync_queue', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('relatorios_agendados', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('registros_ponto', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias_estoque', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('giro_estoque', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.alter_column('quantidade_vendida',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('quantidade_minima',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('quantidade',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('produto_lotes', schema=None) as batch_op:
        batch_op.alter_column('quantidade_inicial',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('quantidade',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('quantidade_atual',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('quantidade_anterior',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('quantidade',
               existing_type=sa.Numeric(precision=10, scale=3),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('movimentacoes_caixa', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DATETIME(), nullable=True))
        batch_op.drop_index('idx_login_history_data')
        batch_op.create_index(batch_op.f('idx_login_history_data'), ['data_cadastro'], unique=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DATETIME(), nullable=True))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('justificativas_ponto', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('salario', sa.NUMERIC(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('data_cadastro', sa.DATETIME(), nullable=True))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('funcionario_beneficios', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DATETIME(), nullable=True))
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DATETIME(), nullable=True))
        batch_op.alter_column('plano_status',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('plano',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('regime_tributario',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('funciona_domingo')
        batch_op.drop_column('prefixo_venda')

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('dashboard_metricas', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('contas_receber', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('contas_pagar', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('configuracoes_horario', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.alter_column('tipo_impressora',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('tema')
        batch_op.drop_column('cor_secundaria')
        batch_op.drop_column('cor_primaria')
        batch_op.drop_column('markup_padrao')
        batch_op.drop_column('dias_tolerancia_fiado')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_cadastro', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('data_atualizacao', sa.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('categorias_produto', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('caixas', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('beneficios', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('banco_horas', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
