"""schema_inicial_limpo

Revision ID: 6b9558d2c735
Revises: dcff685232c8
Create Date: 2026-03-15 20:29:30.164655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b9558d2c735'
down_revision = 'dcff685232c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_column('observacoes')
        batch_op.drop_column('permissoes_json')
        batch_op.drop_column('salario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permissoes_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
