"""Adiciona modelo ManutencaoVeiculo

Revision ID: 881aad6ede95
Revises: 07476b2a790d
Create Date: 2026-07-07 18:44:59.421283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '881aad6ede95'
down_revision = '07476b2a790d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manutencoes_veiculo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('veiculo_id', sa.Integer(), nullable=False),
    sa.Column('motorista_id', sa.Integer(), nullable=True),
    sa.Column('despesa_id', sa.Integer(), nullable=True),
    sa.Column('data_manutencao', sa.DateTime(), nullable=False),
    sa.Column('tipo_servico', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('km_atual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('sync_uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['despesa_id'], ['despesas.id'], name=op.f('fk_manutencoes_veiculo_despesa_id_despesas')),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('fk_manutencoes_veiculo_estabelecimento_id_estabelecimentos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['motorista_id'], ['funcionarios.id'], name=op.f('fk_manutencoes_veiculo_motorista_id_funcionarios')),
    sa.ForeignKeyConstraint(['veiculo_id'], ['veiculos.id'], name=op.f('fk_manutencoes_veiculo_veiculo_id_veiculos')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_manutencoes_veiculo')),
    sa.UniqueConstraint('sync_uuid', name=op.f('uq_manutencoes_veiculo_sync_uuid'))
    )
    with op.batch_alter_table('manutencoes_veiculo', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_manutencoes_veiculo_despesa_id'), ['despesa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manutencoes_veiculo_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manutencoes_veiculo_motorista_id'), ['motorista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_manutencoes_veiculo_veiculo_id'), ['veiculo_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manutencoes_veiculo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_manutencoes_veiculo_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_manutencoes_veiculo_motorista_id'))
        batch_op.drop_index(batch_op.f('ix_manutencoes_veiculo_estabelecimento_id'))
        batch_op.drop_index(batch_op.f('ix_manutencoes_veiculo_despesa_id'))

    op.drop_table('manutencoes_veiculo')
    # ### end Alembic commands ###
