"""Add avaria falta bonificacao to PedidoCompraItem

Revision ID: a4a7b50ea341
Revises: bfae8eec317c
Create Date: 2026-07-02 13:18:14.248450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a7b50ea341'
down_revision = 'bfae8eec317c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_avariada', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('quantidade_faltante', sa.Numeric(precision=10, scale=3), nullable=True))
        batch_op.add_column(sa.Column('quantidade_bonificada', sa.Numeric(precision=10, scale=3), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.drop_column('quantidade_bonificada')
        batch_op.drop_column('quantidade_faltante')
        batch_op.drop_column('quantidade_avariada')

    # ### end Alembic commands ###
