"""Reset inicial completo v2

Revision ID: bbdd8b77db20
Revises: e91f32569069
Create Date: 2026-01-21 02:46:07.715118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bbdd8b77db20'
down_revision = 'e91f32569069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bloco_notas')
    op.drop_table('historico_alteracoes')
    op.drop_table('backups')
    op.drop_table('ordem_servico_itens')
    op.drop_table('ordens_servico')
    op.drop_table('transportadoras')
    op.drop_table('analises_preditivas')
    op.drop_table('parametros_sistema')
    op.drop_table('servicos')
    with op.batch_alter_table('caixas', schema=None) as batch_op:
        batch_op.create_index('idx_caixa_data', ['data_abertura'], unique=False)
        batch_op.create_index('idx_caixa_status', ['status'], unique=False)
        batch_op.drop_constraint(batch_op.f('caixas_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('categorias_produto', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('categorias_produto_codigo_key'), type_='unique')
        batch_op.create_index('idx_categoria_nome', ['nome'], unique=False)
        batch_op.create_unique_constraint('uq_categoria_estab_nome', ['estabelecimento_id', 'nome'])
        batch_op.drop_constraint(batch_op.f('categorias_produto_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cpf', sa.String(length=14), nullable=False))
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('limite_credito', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('saldo_devedor', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('valor_total_gasto', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=False))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('numero', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('pais', sa.String(length=50), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               existing_nullable=True)
        batch_op.alter_column('celular',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('total_compras',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_clientes_cpf_cnpj'))
        batch_op.create_index('idx_cliente_cpf', ['cpf'], unique=False)
        batch_op.create_index('idx_cliente_nome', ['nome'], unique=False)
        batch_op.create_unique_constraint('uq_cliente_estab_cpf', ['estabelecimento_id', 'cpf'])
        batch_op.drop_constraint(batch_op.f('clientes_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('frequencia_compras')
        batch_op.drop_column('endereco')
        batch_op.drop_column('segmento_rfm')
        batch_op.drop_column('dias_ultima_compra')
        batch_op.drop_column('cpf_cnpj')
        batch_op.drop_column('valor_medio_compra')

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emitir_nfe', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('emitir_nfce', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('desconto_maximo_funcionario', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('controlar_validade', sa.Boolean(), nullable=True))
        batch_op.alter_column('estabelecimento_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('logo_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('configuracoes_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('exibir_preco_tela')
        batch_op.drop_column('impressao_automatica')
        batch_op.drop_column('meta_vendas_diaria')
        batch_op.drop_column('alertas_whatsapp')
        batch_op.drop_column('tema_escuro')
        batch_op.drop_column('formas_pagamento')
        batch_op.drop_column('meta_vendas_mensal')
        batch_op.drop_column('desconto_maximo_percentual')
        batch_op.drop_column('dashboard_analytics_avancado')
        batch_op.drop_column('tempo_sessao_minutos')
        batch_op.drop_column('dias_alerta_validade')
        batch_op.drop_column('estoque_minimo_padrao')
        batch_op.drop_column('alertas_email')
        batch_op.drop_column('tipo_impressora')
        batch_op.drop_column('alerta_churn_clientes')
        batch_op.drop_column('arredondamento_valores')
        batch_op.drop_column('permitir_venda_sem_estoque')
        batch_op.drop_column('tentativas_senha_bloqueio')
        batch_op.drop_column('alerta_validade_proxima')

    with op.batch_alter_table('contas_pagar', schema=None) as batch_op:
        batch_op.create_index('idx_conta_pagar_status', ['status'], unique=False)
        batch_op.create_index('idx_conta_pagar_vencimento', ['data_vencimento'], unique=False)
        batch_op.drop_constraint(batch_op.f('contas_pagar_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('contas_receber', schema=None) as batch_op:
        batch_op.create_index('idx_conta_receber_cliente', ['cliente_id'], unique=False)
        batch_op.create_index('idx_conta_receber_vencimento', ['data_vencimento'], unique=False)
        batch_op.drop_constraint(batch_op.f('contas_receber_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('dashboard_metricas', schema=None) as batch_op:
        batch_op.alter_column('total_vendas_dia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('ticket_medio_dia',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_vendas_mes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_despesas_mes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('lucro_bruto_mes',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('crescimento_vs_ontem',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('crescimento_mensal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_metricas_data'))
        batch_op.drop_index(batch_op.f('idx_metricas_estab_data'))
        batch_op.drop_constraint(batch_op.f('uix_estab_data'), type_='unique')
        batch_op.create_index('idx_metrica_data', ['data_referencia'], unique=False)
        batch_op.drop_constraint(batch_op.f('dashboard_metricas_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('anomalias_json')
        batch_op.drop_column('tempo_resposta_medio')
        batch_op.drop_column('confianca_previsao')
        batch_op.drop_column('precisao_previsoes')
        batch_op.drop_column('previsoes_json')
        batch_op.drop_column('margem_lucro_mes')
        batch_op.drop_column('meta_diaria')
        batch_op.drop_column('padrao_semanal_json')
        batch_op.drop_column('cross_selling_json')
        batch_op.drop_column('sazonalidade_json')
        batch_op.drop_column('clv_medio')
        batch_op.drop_column('comparativo_ontem_json')
        batch_op.drop_column('vendas_por_hora_json')
        batch_op.drop_column('comparativo_semana_json')
        batch_op.drop_column('comparativo_mes_json')
        batch_op.drop_column('taxa_churn')
        batch_op.drop_column('meta_atingida_dia')

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fornecedor_id', sa.Integer(), nullable=True))
        batch_op.alter_column('valor',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_despesas_estabelecimento_id'))
        batch_op.create_index('idx_despesa_categoria', ['categoria'], unique=False)
        batch_op.create_index('idx_despesa_data', ['data_despesa'], unique=False)
        batch_op.drop_constraint(batch_op.f('despesas_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'fornecedores', ['fornecedor_id'], ['id'])
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_fantasia', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('razao_social', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('inscricao_estadual', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('regime_tributario', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('data_abertura', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('numero', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('pais', sa.String(length=50), nullable=True))
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=18),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=9),
               nullable=False)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.drop_constraint(batch_op.f('estabelecimentos_cnpj_key'), type_='unique')
        batch_op.create_index('idx_estabelecimento_cnpj', ['cnpj'], unique=False)
        batch_op.create_unique_constraint('uq_estabelecimento_cnpj', ['cnpj'])
        batch_op.drop_column('nome')
        batch_op.drop_column('endereco')

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_fantasia', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('razao_social', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('inscricao_estadual', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('contato_telefone', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('classificacao', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_compras', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_total_comprado', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('numero', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('pais', sa.String(length=50), nullable=True))
        batch_op.alter_column('cnpj',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=18),
               nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('cep',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=9),
               nullable=False)
        batch_op.alter_column('cidade',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
        batch_op.create_index('idx_fornecedor_cnpj', ['cnpj'], unique=False)
        batch_op.create_unique_constraint('uq_fornecedor_estab_cnpj', ['estabelecimento_id', 'cnpj'])
        batch_op.drop_constraint(batch_op.f('fornecedores_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')
        batch_op.drop_column('endereco')
        batch_op.drop_column('avaliacao')
        batch_op.drop_column('tempo_medio_entrega')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('taxa_atendimento')
        batch_op.drop_column('contato_comercial')
        batch_op.drop_column('nome')
        batch_op.drop_column('celular_comercial')

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rg', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('data_nascimento', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('celular', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('salario_base', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('permissoes_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('data_cadastro', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cep', sa.String(length=9), nullable=False))
        batch_op.add_column(sa.Column('logradouro', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('numero', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('complemento', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('bairro', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('cidade', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('estado', sa.String(length=2), nullable=False))
        batch_op.add_column(sa.Column('pais', sa.String(length=50), nullable=True))
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('telefone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=15),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('foto_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=500),
               existing_nullable=True)
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('funcionarios_cpf_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('funcionarios_username_key'), type_='unique')
        batch_op.create_index('idx_funcionario_cpf', ['cpf'], unique=False)
        batch_op.create_index('idx_funcionario_estabelecimento', ['estabelecimento_id'], unique=False)
        batch_op.create_unique_constraint('uq_funcionario_estab_cpf', ['estabelecimento_id', 'cpf'])
        batch_op.create_unique_constraint('uq_funcionario_estab_username', ['estabelecimento_id', 'username'])
        batch_op.drop_constraint(batch_op.f('funcionarios_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('created_at')
        batch_op.drop_column('permissoes')
        batch_op.drop_column('status')
        batch_op.drop_column('data_demissao')
        batch_op.drop_column('comissao_percentual')
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.Text(), nullable=True))
        batch_op.create_index('idx_login_history_data', ['created_at'], unique=False)
        batch_op.create_index('idx_login_history_user', ['username'], unique=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('token_hash')

    with op.batch_alter_table('movimentacoes_caixa', schema=None) as batch_op:
        batch_op.create_index('idx_mov_caixa_caixa', ['caixa_id'], unique=False)
        batch_op.create_index('idx_mov_caixa_tipo', ['tipo'], unique=False)
        batch_op.drop_constraint(batch_op.f('movimentacoes_caixa_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('movimentacoes_caixa_caixa_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'caixas', ['caixa_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_compra_id', sa.Integer(), nullable=True))
        batch_op.alter_column('custo_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('valor_total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.create_index('idx_mov_estoque_data', ['created_at'], unique=False)
        batch_op.create_index('idx_mov_estoque_produto', ['produto_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('movimentacoes_estoque_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'pedidos_compra', ['pedido_compra_id'], ['id'])

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.create_index('idx_pagamento_data', ['data_pagamento'], unique=False)
        batch_op.create_index('idx_pagamento_venda', ['venda_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('pagamentos_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('pagamentos_venda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'vendas', ['venda_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.create_index('idx_pedido_item_pedido', ['pedido_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('pedido_compra_itens_pedido_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'pedidos_compra', ['pedido_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('pedidos_compra_numero_pedido_key'), type_='unique')
        batch_op.create_index('idx_pedido_numero', ['numero_pedido'], unique=False)
        batch_op.create_unique_constraint('uq_pedido_estab_numero', ['estabelecimento_id', 'numero_pedido'])
        batch_op.drop_constraint(batch_op.f('pedidos_compra_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categoria_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('codigo_interno', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('ncm', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('origem', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('classificacao_abc', sa.String(length=1), nullable=True))
        batch_op.add_column(sa.Column('controlar_validade', sa.Boolean(), nullable=True))
        batch_op.alter_column('preco_custo',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('preco_venda',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('margem_lucro',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('produtos_codigo_barras_key'), type_='unique')
        batch_op.create_index('idx_produto_categoria', ['categoria_id'], unique=False)
        batch_op.create_index('idx_produto_codigo', ['codigo_interno'], unique=False)
        batch_op.create_index('idx_produto_nome', ['nome'], unique=False)
        batch_op.create_unique_constraint('uq_produto_estab_codigo', ['estabelecimento_id', 'codigo_interno'])
        batch_op.drop_constraint(batch_op.f('produtos_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'categorias_produto', ['categoria_id'], ['id'])
        batch_op.drop_column('localizacao')
        batch_op.drop_column('categoria')
        batch_op.drop_column('dias_estoque')
        batch_op.drop_column('dias_para_vencer')
        batch_op.drop_column('classificação_abc')
        batch_op.drop_column('frequencia_venda')
        batch_op.drop_column('tipo')
        batch_op.drop_column('subcategoria')
        batch_op.drop_column('giro_estoque')
        batch_op.drop_column('fabricante')
        batch_op.drop_column('data_fabricacao')

    with op.batch_alter_table('relatorios_agendados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destinatarios_email_json', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parametros_json', sa.Text(), nullable=True))
        batch_op.drop_constraint(batch_op.f('relatorios_agendados_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('destinatarios_email')
        batch_op.drop_column('analises_incluidas')
        batch_op.drop_column('parametros')

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.alter_column('preco_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('desconto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total_item',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('custo_unitario',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('margem_item',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.create_index('idx_venda_item_produto', ['produto_id'], unique=False)
        batch_op.create_index('idx_venda_item_venda', ['venda_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('venda_itens_venda_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'vendas', ['venda_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('descricao')

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.alter_column('subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('desconto',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('total',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=False)
        batch_op.alter_column('valor_recebido',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('troco',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)
        batch_op.drop_constraint(batch_op.f('vendas_codigo_key'), type_='unique')
        batch_op.create_index('idx_venda_codigo', ['codigo'], unique=False)
        batch_op.create_index('idx_venda_data', ['data_venda'], unique=False)
        batch_op.create_unique_constraint('uq_venda_estab_codigo', ['estabelecimento_id', 'codigo'])
        batch_op.drop_constraint(batch_op.f('vendas_estabelecimento_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('tipo_venda')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_venda', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('vendas_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_constraint('uq_venda_estab_codigo', type_='unique')
        batch_op.drop_index('idx_venda_data')
        batch_op.drop_index('idx_venda_codigo')
        batch_op.create_unique_constraint(batch_op.f('vendas_codigo_key'), ['codigo'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('troco',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('valor_recebido',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('desconto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('subtotal',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('venda_itens_venda_id_fkey'), 'vendas', ['venda_id'], ['id'])
        batch_op.drop_index('idx_venda_item_venda')
        batch_op.drop_index('idx_venda_item_produto')
        batch_op.alter_column('margem_item',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('custo_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('total_item',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('desconto',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('preco_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)

    with op.batch_alter_table('relatorios_agendados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parametros', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('analises_incluidas', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('destinatarios_email', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('relatorios_agendados_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_column('parametros_json')
        batch_op.drop_column('destinatarios_email_json')

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_fabricacao', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fabricante', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('giro_estoque', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('subcategoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('frequencia_venda', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('classificação_abc', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dias_para_vencer', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dias_estoque', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('localizacao', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('produtos_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_constraint('uq_produto_estab_codigo', type_='unique')
        batch_op.drop_index('idx_produto_nome')
        batch_op.drop_index('idx_produto_codigo')
        batch_op.drop_index('idx_produto_categoria')
        batch_op.create_unique_constraint(batch_op.f('produtos_codigo_barras_key'), ['codigo_barras'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('margem_lucro',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('preco_venda',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.alter_column('preco_custo',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('controlar_validade')
        batch_op.drop_column('classificacao_abc')
        batch_op.drop_column('origem')
        batch_op.drop_column('ncm')
        batch_op.drop_column('codigo_interno')
        batch_op.drop_column('categoria_id')

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pedidos_compra_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_constraint('uq_pedido_estab_numero', type_='unique')
        batch_op.drop_index('idx_pedido_numero')
        batch_op.create_unique_constraint(batch_op.f('pedidos_compra_numero_pedido_key'), ['numero_pedido'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pedido_compra_itens_pedido_id_fkey'), 'pedidos_compra', ['pedido_id'], ['id'])
        batch_op.drop_index('idx_pedido_item_pedido')

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('pagamentos_venda_id_fkey'), 'vendas', ['venda_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('pagamentos_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_index('idx_pagamento_venda')
        batch_op.drop_index('idx_pagamento_data')

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('movimentacoes_estoque_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_index('idx_mov_estoque_produto')
        batch_op.drop_index('idx_mov_estoque_data')
        batch_op.alter_column('valor_total',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('custo_unitario',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.drop_column('pedido_compra_id')

    with op.batch_alter_table('movimentacoes_caixa', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('movimentacoes_caixa_caixa_id_fkey'), 'caixas', ['caixa_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('movimentacoes_caixa_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_index('idx_mov_caixa_tipo')
        batch_op.drop_index('idx_mov_caixa_caixa')

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_index('idx_login_history_user')
        batch_op.drop_index('idx_login_history_data')
        batch_op.drop_column('user_agent')

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comissao_percentual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('data_demissao', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permissoes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('funcionarios_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_constraint('uq_funcionario_estab_username', type_='unique')
        batch_op.drop_constraint('uq_funcionario_estab_cpf', type_='unique')
        batch_op.drop_index('idx_funcionario_estabelecimento')
        batch_op.drop_index('idx_funcionario_cpf')
        batch_op.create_unique_constraint(batch_op.f('funcionarios_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('funcionarios_cpf_key'), ['cpf'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('role',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('foto_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('pais')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
        batch_op.drop_column('data_cadastro')
        batch_op.drop_column('permissoes_json')
        batch_op.drop_column('salario_base')
        batch_op.drop_column('celular')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('rg')

    with op.batch_alter_table('fornecedores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('celular_comercial', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('contato_comercial', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('taxa_atendimento', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_medio_entrega', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('avaliacao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fornecedores_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_constraint('uq_fornecedor_estab_cnpj', type_='unique')
        batch_op.drop_index('idx_fornecedor_cnpj')
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.drop_column('pais')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('valor_total_comprado')
        batch_op.drop_column('total_compras')
        batch_op.drop_column('classificacao')
        batch_op.drop_column('contato_telefone')
        batch_op.drop_column('inscricao_estadual')
        batch_op.drop_column('razao_social')
        batch_op.drop_column('nome_fantasia')

    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('endereco', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_estabelecimento_cnpj', type_='unique')
        batch_op.drop_index('idx_estabelecimento_cnpj')
        batch_op.create_unique_constraint(batch_op.f('estabelecimentos_cnpj_key'), ['cnpj'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('estado',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)
        batch_op.alter_column('cidade',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('cep',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('cnpj',
               existing_type=sa.String(length=18),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('pais')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('data_abertura')
        batch_op.drop_column('regime_tributario')
        batch_op.drop_column('inscricao_estadual')
        batch_op.drop_column('razao_social')
        batch_op.drop_column('nome_fantasia')

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('despesas_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_index('idx_despesa_data')
        batch_op.drop_index('idx_despesa_categoria')
        batch_op.create_index(batch_op.f('ix_despesas_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.alter_column('valor',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
        batch_op.drop_column('fornecedor_id')

    with op.batch_alter_table('dashboard_metricas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meta_atingida_dia', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('taxa_churn', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comparativo_mes_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comparativo_semana_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vendas_por_hora_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comparativo_ontem_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('clv_medio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sazonalidade_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cross_selling_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('padrao_semanal_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meta_diaria', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('margem_lucro_mes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('previsoes_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('precisao_previsoes', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('confianca_previsao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_resposta_medio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('anomalias_json', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('dashboard_metricas_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_index('idx_metrica_data')
        batch_op.create_unique_constraint(batch_op.f('uix_estab_data'), ['estabelecimento_id', 'data_referencia'], postgresql_nulls_not_distinct=False)
        batch_op.create_index(batch_op.f('idx_metricas_estab_data'), ['estabelecimento_id', 'data_referencia'], unique=False)
        batch_op.create_index(batch_op.f('idx_metricas_data'), ['data_referencia'], unique=False)
        batch_op.alter_column('crescimento_mensal',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('crescimento_vs_ontem',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('lucro_bruto_mes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('total_despesas_mes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('total_vendas_mes',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('ticket_medio_dia',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('total_vendas_dia',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('contas_receber', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contas_receber_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_index('idx_conta_receber_vencimento')
        batch_op.drop_index('idx_conta_receber_cliente')

    with op.batch_alter_table('contas_pagar', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('contas_pagar_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_index('idx_conta_pagar_vencimento')
        batch_op.drop_index('idx_conta_pagar_status')

    with op.batch_alter_table('configuracoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alerta_validade_proxima', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tentativas_senha_bloqueio', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('permitir_venda_sem_estoque', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('arredondamento_valores', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alerta_churn_clientes', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tipo_impressora', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alertas_email', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('estoque_minimo_padrao', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dias_alerta_validade', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tempo_sessao_minutos', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dashboard_analytics_avancado', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('desconto_maximo_percentual', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meta_vendas_mensal', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('formas_pagamento', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tema_escuro', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('alertas_whatsapp', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('meta_vendas_diaria', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('impressao_automatica', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('exibir_preco_tela', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('configuracoes_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.alter_column('logo_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('estabelecimento_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('controlar_validade')
        batch_op.drop_column('desconto_maximo_funcionario')
        batch_op.drop_column('emitir_nfce')
        batch_op.drop_column('emitir_nfe')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_medio_compra', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cpf_cnpj', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dias_ultima_compra', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('segmento_rfm', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('endereco', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('frequencia_compras', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('clientes_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_constraint('uq_cliente_estab_cpf', type_='unique')
        batch_op.drop_index('idx_cliente_nome')
        batch_op.drop_index('idx_cliente_cpf')
        batch_op.create_index(batch_op.f('ix_clientes_cpf_cnpj'), ['cpf_cnpj'], unique=True)
        batch_op.alter_column('ativo',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('total_compras',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
        batch_op.alter_column('celular',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('telefone',
               existing_type=sa.String(length=15),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
        batch_op.drop_column('pais')
        batch_op.drop_column('estado')
        batch_op.drop_column('cidade')
        batch_op.drop_column('bairro')
        batch_op.drop_column('complemento')
        batch_op.drop_column('numero')
        batch_op.drop_column('logradouro')
        batch_op.drop_column('cep')
        batch_op.drop_column('valor_total_gasto')
        batch_op.drop_column('saldo_devedor')
        batch_op.drop_column('limite_credito')
        batch_op.drop_column('data_nascimento')
        batch_op.drop_column('rg')
        batch_op.drop_column('cpf')

    with op.batch_alter_table('categorias_produto', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('categorias_produto_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_constraint('uq_categoria_estab_nome', type_='unique')
        batch_op.drop_index('idx_categoria_nome')
        batch_op.create_unique_constraint(batch_op.f('categorias_produto_codigo_key'), ['codigo'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('caixas', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('caixas_estabelecimento_id_fkey'), 'estabelecimentos', ['estabelecimento_id'], ['id'])
        batch_op.drop_index('idx_caixa_status')
        batch_op.drop_index('idx_caixa_data')

    op.create_table('servicos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valor', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('duracao', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('categoria', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('servicos_estabelecimento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('servicos_pkey')),
    sa.UniqueConstraint('codigo', name=op.f('servicos_codigo_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('parametros_sistema',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('chave', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('valor', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('grupo', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('parametros_sistema_estabelecimento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('parametros_sistema_pkey')),
    sa.UniqueConstraint('estabelecimento_id', 'chave', name=op.f('uq_parametro_estab_chave'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('analises_preditivas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('parametros', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('metricas', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dados_treinamento_inicio', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dados_treinamento_fim', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('tamanho_treinamento', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('ultimo_treinamento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('proximo_treinamento', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('precisao', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('recall', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('f1_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('analises_preditivas_estabelecimento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('analises_preditivas_pkey'))
    )
    op.create_table('transportadoras',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('nome_fantasia', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('razao_social', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('cnpj', sa.VARCHAR(length=18), autoincrement=False, nullable=False),
    sa.Column('telefone', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('contato', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('telefone_contato', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('taxa_frete', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('prazo_entrega', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('cep', sa.VARCHAR(length=9), autoincrement=False, nullable=False),
    sa.Column('logradouro', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('numero', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('complemento', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('bairro', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('cidade', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('estado', sa.VARCHAR(length=2), autoincrement=False, nullable=False),
    sa.Column('pais', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('transportadoras_estabelecimento_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('transportadoras_pkey'))
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('ordens_servico_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cliente_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('numero_os', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('equipamento', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('problema', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('diagnostico', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('solucao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('valor_servico', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('valor_pecas', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('valor_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True),
    sa.Column('data_abertura', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('data_previsao', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('data_conclusao', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('garantia', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], name='ordens_servico_cliente_id_fkey'),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name='ordens_servico_estabelecimento_id_fkey'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name='ordens_servico_funcionario_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='ordens_servico_pkey'),
    sa.UniqueConstraint('numero_os', name='ordens_servico_numero_os_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('ordem_servico_itens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ordem_servico_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('produto_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('valor_unitario', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('valor_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ordem_servico_id'], ['ordens_servico.id'], name=op.f('ordem_servico_itens_ordem_servico_id_fkey')),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('ordem_servico_itens_produto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ordem_servico_itens_pkey'))
    )
    op.create_table('backups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nome_arquivo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('tamanho', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('tipo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('caminho', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('hash_arquivo', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('observacoes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('backups_estabelecimento_id_fkey')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('backups_funcionario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('backups_pkey'))
    )
    op.create_table('historico_alteracoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tabela', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('registro_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acao', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('dados_anteriores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('dados_novos', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('historico_alteracoes_estabelecimento_id_fkey')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('historico_alteracoes_funcionario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('historico_alteracoes_pkey'))
    )
    op.create_table('bloco_notas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('estabelecimento_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('funcionario_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titulo', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('conteudo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('cor', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('fixado', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('bloco_notas_estabelecimento_id_fkey')),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('bloco_notas_funcionario_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('bloco_notas_pkey'))
    )
    # ### end Alembic commands ###
