"""add_indexes_to_foreign_keys

Revision ID: bfae8eec317c
Revises: 1e7f4460e868
Create Date: 2026-07-01 21:15:09.686235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfae8eec317c'
down_revision = '1e7f4460e868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditoria_usuario_id'), ['usuario_id'], unique=False)

    with op.batch_alter_table('banco_horas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_banco_horas_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('caixas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caixas_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_rota_id'), ['rota_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_tabela_preco_id'), ['tabela_preco_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_clientes_vendedor_id'), ['vendedor_id'], unique=False)

    with op.batch_alter_table('contas_pagar', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contas_pagar_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contas_pagar_pedido_compra_id'), ['pedido_compra_id'], unique=False)

    with op.batch_alter_table('contas_receber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contas_receber_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_contas_receber_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('custos_entrega', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_custos_entrega_motorista_id'), ['motorista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_custos_entrega_veiculo_id'), ['veiculo_id'], unique=False)

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_despesas_fornecedor_id'), ['fornecedor_id'], unique=False)

    with op.batch_alter_table('documentos_fiscais', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documentos_fiscais_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documentos_fiscais_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('entrega_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrega_itens_entrega_id'), ['entrega_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrega_itens_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrega_itens_venda_item_id'), ['venda_item_id'], unique=False)

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entregas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entregas_motorista_id'), ['motorista_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entregas_taxa_entrega_id'), ['taxa_entrega_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entregas_veiculo_id'), ['veiculo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entregas_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('funcionario_beneficios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_funcionario_beneficios_beneficio_id'), ['beneficio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_funcionario_beneficios_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historico_precos_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_historico_precos_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('justificativas_ponto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_justificativas_ponto_aprovador_id'), ['aprovador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_justificativas_ponto_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_login_history_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('metas_vendedor', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metas_vendedor_vendedor_id'), ['vendedor_id'], unique=False)

    with op.batch_alter_table('movimentacoes_caixa', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_caixa_caixa_id'), ['caixa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_caixa_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_funcionario_id'), ['funcionario_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_lote_id'), ['lote_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_pedido_compra_id'), ['pedido_compra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('notas_fiscais_entrada', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notas_fiscais_entrada_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notas_fiscais_entrada_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pagamentos_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_compra_itens_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_compra_itens_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('pedido_venda_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedido_venda_itens_pedido_id'), ['pedido_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedido_venda_itens_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_compra_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_compra_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('pedidos_venda', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pedidos_venda_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pedidos_venda_vendedor_id'), ['vendedor_id'], unique=False)

    with op.batch_alter_table('produto_lotes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produto_lotes_fornecedor_id'), ['fornecedor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_lotes_pedido_compra_id'), ['pedido_compra_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produto_lotes_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_categoria_id'), ['categoria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_fornecedor_id'), ['fornecedor_id'], unique=False)

    with op.batch_alter_table('produtos_foco', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_foco_produto_id'), ['produto_id'], unique=False)

    with op.batch_alter_table('rastreamento_entregas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rastreamento_entregas_entrega_id'), ['entrega_id'], unique=False)

    with op.batch_alter_table('registros_ponto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_ponto_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('rotas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rotas_vendedor_id'), ['vendedor_id'], unique=False)

    with op.batch_alter_table('tabela_preco_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tabela_preco_itens_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tabela_preco_itens_tabela_id'), ['tabela_id'], unique=False)

    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_veiculos_motorista_id'), ['motorista_id'], unique=False)

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venda_itens_produto_id'), ['produto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_venda_itens_venda_id'), ['venda_id'], unique=False)

    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendas_caixa_id'), ['caixa_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_cliente_id'), ['cliente_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vendas_funcionario_id'), ['funcionario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_vendas_cliente_id'))
        batch_op.drop_index(batch_op.f('ix_vendas_caixa_id'))

    with op.batch_alter_table('venda_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venda_itens_venda_id'))
        batch_op.drop_index(batch_op.f('ix_venda_itens_produto_id'))

    with op.batch_alter_table('veiculos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_veiculos_motorista_id'))

    with op.batch_alter_table('tabela_preco_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tabela_preco_itens_tabela_id'))
        batch_op.drop_index(batch_op.f('ix_tabela_preco_itens_produto_id'))

    with op.batch_alter_table('rotas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rotas_vendedor_id'))

    with op.batch_alter_table('registros_ponto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_ponto_funcionario_id'))

    with op.batch_alter_table('rastreamento_entregas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rastreamento_entregas_entrega_id'))

    with op.batch_alter_table('produtos_foco', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_foco_produto_id'))

    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_fornecedor_id'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria_id'))

    with op.batch_alter_table('produto_lotes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produto_lotes_produto_id'))
        batch_op.drop_index(batch_op.f('ix_produto_lotes_pedido_compra_id'))
        batch_op.drop_index(batch_op.f('ix_produto_lotes_fornecedor_id'))

    with op.batch_alter_table('pedidos_venda', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_venda_vendedor_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_venda_cliente_id'))

    with op.batch_alter_table('pedidos_compra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_pedidos_compra_fornecedor_id'))

    with op.batch_alter_table('pedido_venda_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_venda_itens_produto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_venda_itens_pedido_id'))

    with op.batch_alter_table('pedido_compra_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pedido_compra_itens_produto_id'))
        batch_op.drop_index(batch_op.f('ix_pedido_compra_itens_pedido_id'))

    with op.batch_alter_table('pagamentos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pagamentos_venda_id'))

    with op.batch_alter_table('notas_fiscais_entrada', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_entrada_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_notas_fiscais_entrada_fornecedor_id'))

    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_venda_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_produto_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_pedido_compra_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_lote_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_funcionario_id'))

    with op.batch_alter_table('movimentacoes_caixa', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_caixa_venda_id'))
        batch_op.drop_index(batch_op.f('ix_movimentacoes_caixa_caixa_id'))

    with op.batch_alter_table('metas_vendedor', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metas_vendedor_vendedor_id'))

    with op.batch_alter_table('login_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_login_history_funcionario_id'))

    with op.batch_alter_table('justificativas_ponto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_justificativas_ponto_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_justificativas_ponto_aprovador_id'))

    with op.batch_alter_table('historico_precos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historico_precos_produto_id'))
        batch_op.drop_index(batch_op.f('ix_historico_precos_funcionario_id'))

    with op.batch_alter_table('funcionario_beneficios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_funcionario_beneficios_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_funcionario_beneficios_beneficio_id'))

    with op.batch_alter_table('entregas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entregas_venda_id'))
        batch_op.drop_index(batch_op.f('ix_entregas_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_entregas_taxa_entrega_id'))
        batch_op.drop_index(batch_op.f('ix_entregas_motorista_id'))
        batch_op.drop_index(batch_op.f('ix_entregas_cliente_id'))

    with op.batch_alter_table('entrega_itens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrega_itens_venda_item_id'))
        batch_op.drop_index(batch_op.f('ix_entrega_itens_produto_id'))
        batch_op.drop_index(batch_op.f('ix_entrega_itens_entrega_id'))

    with op.batch_alter_table('documentos_fiscais', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_fiscais_venda_id'))
        batch_op.drop_index(batch_op.f('ix_documentos_fiscais_funcionario_id'))

    with op.batch_alter_table('despesas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_despesas_fornecedor_id'))

    with op.batch_alter_table('custos_entrega', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_custos_entrega_veiculo_id'))
        batch_op.drop_index(batch_op.f('ix_custos_entrega_motorista_id'))

    with op.batch_alter_table('contas_receber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_receber_venda_id'))
        batch_op.drop_index(batch_op.f('ix_contas_receber_cliente_id'))

    with op.batch_alter_table('contas_pagar', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contas_pagar_pedido_compra_id'))
        batch_op.drop_index(batch_op.f('ix_contas_pagar_fornecedor_id'))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_vendedor_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_tabela_preco_id'))
        batch_op.drop_index(batch_op.f('ix_clientes_rota_id'))

    with op.batch_alter_table('caixas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caixas_funcionario_id'))

    with op.batch_alter_table('banco_horas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banco_horas_funcionario_id'))

    with op.batch_alter_table('auditoria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditoria_usuario_id'))

    # ### end Alembic commands ###
