"""Adicionar data_fabricacao e dias_para_vencer aos produtos

Revision ID: c1976dcb3139
Revises: 3f8f8d0a4c1b
Create Date: 2026-01-05 20:57:55.463647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1976dcb3139'
down_revision = '3f8f8d0a4c1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_fabricacao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dias_para_vencer', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('dias_para_vencer')
        batch_op.drop_column('data_fabricacao')

    # ### end Alembic commands ###
