"""Add CRM credit metrics to Cliente

Revision ID: d2299b1ad288
Revises: 3bed2e4d3fea
Create Date: 2026-07-07 15:39:19.096476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd2299b1ad288'
down_revision = '3bed2e4d3fea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score_credito', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('bom_pagador', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('risco_inadimplencia', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('atraso_medio_dias', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('atraso_medio_dias')
        batch_op.drop_column('risco_inadimplencia')
        batch_op.drop_column('bom_pagador')
        batch_op.drop_column('score_credito')

    # ### end Alembic commands ###
