"""adicionar campos de rastreabilidade lote data_fabricacao data_validade

Revision ID: d31cf4ee8e85
Revises: c1976dcb3139
Create Date: 2026-01-05 21:02:18.374696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31cf4ee8e85'
down_revision = 'c1976dcb3139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('data_fabricacao', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('dias_para_vencer', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('dias_para_vencer')
        batch_op.drop_column('data_fabricacao')

    # ### end Alembic commands ###
