"""add_consultor_interacao

Revision ID: d73ed9f4ed75
Revises: 881aad6ede95
Create Date: 2026-07-11 17:10:56.189846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73ed9f4ed75'
down_revision = '881aad6ede95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consultor_interacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=True),
    sa.Column('especialista', sa.String(length=40), nullable=False),
    sa.Column('pergunta', sa.Text(), nullable=False),
    sa.Column('resposta', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=10), nullable=False),
    sa.Column('duracao_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], name=op.f('fk_consultor_interacoes_estabelecimento_id_estabelecimentos'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], name=op.f('fk_consultor_interacoes_funcionario_id_funcionarios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consultor_interacoes'))
    )
    with op.batch_alter_table('consultor_interacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_consultor_interacoes_estabelecimento_id'), ['estabelecimento_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_consultor_interacoes_funcionario_id'), ['funcionario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultor_interacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_consultor_interacoes_funcionario_id'))
        batch_op.drop_index(batch_op.f('ix_consultor_interacoes_estabelecimento_id'))

    op.drop_table('consultor_interacoes')
    # ### end Alembic commands ###
