"""Add SFA models: TabelaPreco, Rota, PedidoVenda

Revision ID: f8efae926d7f
Revises: d0e1f2a3b4c5
Create Date: 2026-06-24 13:52:50.410672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8efae926d7f'
down_revision = 'd0e1f2a3b4c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tabela_preco_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rota_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_clientes_rota_id_rotas'), 'rotas', ['rota_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_clientes_tabela_preco_id_tabelas_preco'), 'tabelas_preco', ['tabela_preco_id'], ['id'])

    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.drop_column('stripe_subscription_id')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('estabelecimentos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_clientes_tabela_preco_id_tabelas_preco'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_clientes_rota_id_rotas'), type_='foreignkey')
        batch_op.drop_column('rota_id')
        batch_op.drop_column('tabela_preco_id')

    # ### end Alembic commands ###
